### ISSUE TITLE
GoogleStrategy should allow custom scopes

### ISSUE THREAD

**Issue by agcty** [TheRealFlyingCoder/remix-auth-socials#21]
### Describe the bug

Right now, the Google Strategy only allows for the "openid", "profile" & "email" scopes, however, there are many custom scopes that can be used with Google such as "https://www.googleapis.com/auth/business.manage" or "https://www.googleapis.com/auth/plus.business.manage". I propose changing the GoogleScope type to a simple string.

**Comment by mel-types-codes** [comment]
Hey @agcty I think this is awesome, I have been waiting to use the library for our apps Auth but we need calendar scopes for Google and Microsoft. Any idea when this will be available? I appreciate all your hard work!

**Comment by TheRealFlyingCoder** [comment]
Hey @agcty  and @mel-types-codes!

I've just released V2 which brings in the [remix-auth-google](https://github.com/pbteja1998/remix-auth-google) package.

I made a PR over there and now it accepts both the typed array, or custom string scope like you wanted :)

On top of that, if there are other scopes allowed in the array you should definitely make a PR to update the Scope type for everyone else who will use it!
