### ISSUE TITLE
DiscordStrategy is not calling verify function

### ISSUE THREAD

**Issue by mezodev0** [TheRealFlyingCoder/remix-auth-socials#22]
### Describe the bug

When using the DiscordStrategy, the verify function should be called after the authentication is completed. However, when checking the session data, it only returns something called "oauth2:state" with the according state that was passed to discord.
When trying to log something in the verify function, nothing is being printed out.

### Your Example Website or App

https://github.com/mezodev0/shishabot-web

### Steps to Reproduce the Bug or Issue

1. Create an Application via [https://discord.com/developers/applications](url)
2. Copy paste .env.example
3. Fill out values
4. Start project
5. Click the link to the login page
6. Click on the login button
7. Authenticate via Discord

### Expected behavior

I expected the discord user to be returned, but I am getting nothing. 

### Platform

- OS: Ubuntu Linux
- Browser: Firefox

**Comment by TheRealFlyingCoder** [comment]
Hey!

Sorry for being slow on this.

I just released V2 of the package which brings in the remix-auth-discord package directly.

If the issue still persists in that package the issue will have to be directed there :)
