### ISSUE TITLE
TS complains about usage of SocialsProvider

### ISSUE THREAD

**Issue by kwiat1990** [TheRealFlyingCoder/remix-auth-socials#25]
### Describe the bug

After update to the newest version (`2.0.1`) the following code from the documentation doesn't compile:

```ts
// app/server/auth.server.ts
import { Authenticator } from "remix-auth";
import { GoogleStrategy, FacebookStrategy, SocialsProvider } from "remix-auth-socials";
import { sessionStorage } from "~/services/session.server";

// Create an instance of the authenticator
export let authenticator = new Authenticator(sessionStorage, { sessionKey: '_session' });
// You may specify a <User> type which the strategies will return (this will be stored in the session)
// export let authenticator = new Authenticator<User>(sessionStorage, { sessionKey: '_session' });

const getCallback = (provider: SocialsProvider) => {
  return `http://localhost:3333/auth/${provider}/callback`
} 

authenticator.use(new GoogleStrategy(
  {
    clientID: "YOUR_CLIENT_ID",
    clientSecret: "YOUR_CLIENT_SECRET",
    callbackURL: getCallback(SocialsProvider.GOOGLE)
  },
  async ({ profile }) => {
    // here you would find or create a user in your database
    return profile;
  }
));

authenticator.use(new FacebookStrategy(
  {
    clientID: "YOUR_CLIENT_ID",
    clientSecret: "YOUR_CLIENT_SECRET",
    callbackURL: getCallback(SocialsProvider.FACEBOOK)
  },
  async ({ profile }) => {}
));
```

TS complains: `'SocialsProvider' refers to a value, but is being used as a type here. Did you mean 'typeof SocialsProvider'?`. After changing function signature to `provider: typeof SocialsProvider` TS complains regarding passing in `SocialsProvider.XXX` into `getCallback`: `Argument of type 'string' is not assignable to parameter of type '{ readonly DISCORD: "discord"; readonly FACEBOOK: "facebook"; readonly GITHUB: "github"; readonly GOOGLE: "google"; readonly MICROSOFT: "microsoft"; readonly TWITTER: "twitter"; }'`.

In order to use `SocialsProvider` the function signature needs to looks as follows: `getCallback(provider: typeof SocialsProvider[keyof typeof SocialsProvider])`, which isn't the perfect for an exported type.

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Update plugin to the newest version (`2.0.1`).
2. Use code from the docs.
3. TS will complain about usage of `SocialsProvider.

### Expected behavior

The code compiles.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by TheRealFlyingCoder** [comment]
I've just released a patch that should resolve this

The problem was switching from an Enum with inferred type usage to a const which is necessary to re-export the package names.

I just added:

`export type SocialsProvider = typeof SocialsProvider[keyof typeof SocialsProvider];`

Which will pick up when you try to use the type, should be no change required :)

**Comment by m5r** [comment]
Now the error that appears is `TS2702: 'SocialsProvider' only refers to a type, but is being used as a namespace here.` :sweat_smile:

**Comment by TheRealFlyingCoder** [comment]
Ahh this is an unusual, what's the use case you need to care about it?

If you don't implement a specific social in your authenticator it will fail gracefully if anyone happens to hit the endpoint

Regardless of that though the easier solution is `Extract<SocialsProvider, 'google' | 'github'>`

**Comment by m5r** [comment]
I'm using this to type the social providers the app explicitly supports like this:

```ts
// helper.ts
type SupportedSocialProvider = SocialsProvider.GOOGLE | SocialsProvider.GITHUB;
const supportedSocialProviders: SupportedSocialProvider[] = [SocialsProvider.GOOGLE, SocialsProvider.GITHUB];
export function validateSocialProvider(provider: any): provider is SupportedSocialProvider {
	return supportedSocialProviders.includes(provider);
}

// sign-in/$provider.tsx
export async function action({ request, params }: ActionArgs) {
	const provider = params.provider;
	if (!validateSocialProvider(provider)) {
		return redirect("/sign-in");
	}

	return await authenticator.authenticate(provider, request);
}
```

---

I just noticed I don't need that weird glob import `import * as ...` so I'm going with this approach and call it a day:
`type SupportedSocialProvider = typeof SocialsProvider.GOOGLE | typeof SocialsProvider.GITHUB;`
