### ISSUE TITLE
Login with Linkedin is not available

### ISSUE THREAD

**Issue by se7entyse7en** [TheRealFlyingCoder/remix-auth-socials#30]
### Describe the bug

It's probably caused by [this](https://github.com/TheRealFlyingCoder/remix-auth-socials/actions/runs/7352673313).

In the latest version of the code in NPM there's no Linkedin social provider. It can also be checked directly in NPM [here](https://www.npmjs.com/package/remix-auth-socials?activeTab=code).

### Your Example Website or App

placeholder just to make the submission form happy

### Steps to Reproduce the Bug or Issue

It's simply not there.

### Expected behavior

I expect the source code in Github to be aligned with what is uploaded in NPM

### Screenshots or Videos

<img width="553" alt="Screenshot 2024-04-02 at 12 01 31" src="https://github.com/TheRealFlyingCoder/remix-auth-socials/assets/5599208/91be7414-ce7d-41b2-95b1-f079dd1d975a">

### Platform

- OS: All
- Browser: All
- Version: 2.0.6

**Comment by se7entyse7en** [comment]
This is probably caused by both:
- https://github.com/Lzok/remix-auth-linkedin/issues/3
- https://github.com/Lzok/remix-auth-linkedin/issues/4

**Comment by naourass** [comment]
Any workaround to make LinkedIn auth work?

**Comment by Lzok** [comment]
Hello there! I just published the version `v2.0.1` for the `remix-auth-linkedin` package. Can you please confirm if that works well for you?
I will be paying atention to this.

Thank you!

**Comment by TheRealFlyingCoder** [comment]
Sorry for the delay on this!

V2.1.0 just released which tidies up the last of these missing links, so everything should be aligned now! 🎉
