### ISSUE TITLE
LinkedIn Strategy (another package)

### ISSUE THREAD

**Issue by Lzok** [TheRealFlyingCoder/remix-auth-socials#5]
Hi, how are you?

I'm just passing here to show you I made a package for [LinkedIn Strategy](https://github.com/Lzok/remix-auth-linkedin).
I red your message in [this other issue of yours](https://github.com/TheRealFlyingCoder/remix-auth-socials/issues/3) and you have valid points.

I documented the code, made tests and export some other things among the main class. [Here is the source code to look at it](https://github.com/Lzok/remix-auth-linkedin/blob/main/src/index.ts)

Let me know how you see it, if you consider i am missing something for you so you can re-export from there. Feedback and suggestions are welcome.

Have a nice Saturday!

**Comment by TheRealFlyingCoder** [comment]
Hey!

Sorry I took so long on this. I will be re-exporting third party packages soon!

**Comment by bluefire2121** [comment]
Any update on the LinkedIn Strategy export?

**Comment by TheRealFlyingCoder** [comment]
@Lzok and @bluefire2121 boy am I sorry this took so long!!!!!

I've just had all the social auth packages (bar facebook) approve my PR's to ensure they offer a consistent experience, and released V2 of the package.

@Lzok  have a look at [the google package](https://github.com/pbteja1998/remix-auth-google/blob/main/src/index.ts) and once you've updated remix-auth-linkedin to match the experience open a PR to add it here :)

We just need scopes as either `scopes?: LinkedinScopes[] | string` as well as a LinkedInStrategyDefaultName export... Essentially just follow the pattern and we'll be good :)
