### ISSUE TITLE
The README is not up to date with the code

### ISSUE THREAD

**Issue by pal** [TheRealFlyingCoder/remix-auth-socials#7]
Hi! Thanks for your efforts with this project!

I noticed that the README code examples do not match the actual code that is needed. 

Some examples:
* References to `SocialProvider` should be `SocialsProvider`
* Imports for `~/auth.server` should be for `~/server/auth.server`
* `login.tsx` is missing enclosing jsx tag
* `auth.server.ts` is missing required imports and is referencing non-existant code

I'll try to get this working, then I can supply a PR (only started with remix 1 hour ago 😅)

**Comment by TheRealFlyingCoder** [comment]
This is awesome! Thanks for the help
